/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
// look at page 19 in datasheet for block diagram of micro
// All addresses are accessed by offset from a base address
#define RCC 0x40023800
#define RCC_AHB1_CLOCK_ENABLE_REG (RCC+0x30)

#define GPIOD 0x40020C00
#define GPIOD_PORT_MODE_REG 0x40020C00
#define GPIOD_OUTPUT_DATA_REG (GPIOD+0x14)

#define GPIOA 0x40020000
#define GPIOA_PORT_MODE_REG 0x40020000
#define GPIOA_INPUT_DATA_REG (GPIOA+0x10)


#include <stdio.h>
#include <stdint.h>

int main(void)
{
	// pointers to clock, port registers addresses to intialize hardware and retrieve data
	int32_t* pRCC_Clock_enable = (int32_t*) RCC_AHB1_CLOCK_ENABLE_REG;
	int32_t* pGPIOD_Port_Mode_reg = (int32_t*) GPIOD_PORT_MODE_REG;
	int32_t* pGPIOD_Output_Data_reg = (int32_t*) GPIOD_OUTPUT_DATA_REG;

	int32_t* pGPIOA_Port_Mode_reg = (int32_t*) GPIOA_PORT_MODE_REG;
	int32_t* pGPIOA_Input_Data_reg = (int32_t*) GPIOA_INPUT_DATA_REG;

	*pRCC_Clock_enable |= (1 << 3) ;
	*pRCC_Clock_enable |= 1;

	int32_t temp = ~(3 << 24);

	*pGPIOD_Port_Mode_reg &= temp;
	*pGPIOD_Port_Mode_reg |= (1 << 24);

	*pGPIOD_Output_Data_reg |= (1 << 12);

	*pGPIOA_Port_Mode_reg &= ~(3);

	int8_t PA0_state = 0;

	while(1){
//		checking the state of GPIOA input data register, 1 if the button is held down
		PA0_state = (int8_t)(*pGPIOA_Input_Data_reg & 1);
		if(PA0_state){
			// turning on LED
			*pGPIOD_Output_Data_reg |= (1 << 12);
		}else{*pGPIOD_Output_Data_reg &= ~(1 << 12);}
	}


	/* Pseudo code
	 * clear bits of RCC AHB reg
	 * move value into RCC AHB reg to enable clock to GPIO D
	 * clear bits of Port mode
	 * move value into Port mode to turn pin 12 to output
	 * clear bits of output data
	 * move value into output data reg to turn pin 12 to output value
	 * END*/
}





